### ISSUE TITLE
SSH scheduler AttributeError

### ISSUE THREAD

**Issue by joasode** [reframe-hpc/reframe#3582]
I have a setup where we have two workstations where the host have ReFrame installed and the test executes on the remote using `--system remote` and this ReFrame config.py
```
site_configuration = {
  "systems": [
    {
      "name": "host",
      "descr": "Host system",
      "hostnames": [".*"],
      "partitions": [
        {
          "name": "default",
          "scheduler": "local",
          "launcher": "local",
          "environs": ["builtin"]
        }
      ]
    },
    {
      "name": "remote",
      "descr": "Remote system",
      "hostnames": [".*"],
      "partitions": [
        {
          "name": "default",
          "scheduler": "ssh",
          "sched_options": {"ssh_hosts": ['remote.host']},
          "launcher": "local",
          "access": [''],
          "environs": ["builtin"]
        }
      ]
    }  
  ],
...
```
The test is a RunOnlyRegressionTest that activates a Python venv and runs an executable with a file input and extracts performance from the stdout.
The Error:
```
  File "/home/joaso/reframe-tests/.venv/lib/python3.12/site-packages/reframe/core/schedulers/ssh.py", line 214, in _poll_job
    ferr.write(exec_proc.stderr().read())
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'read'
```
and similarly for `exec_proc.stdout().read()` on line 211.
Temporary fix:
Remove the `.read()` results in the expected behavior.

**Comment by vkarak** [comment]
This is a bug introduced in #3556. The `.read()` is not needed anymore.
